<#
=============================================================================
 doppler-pull-env.ps1 - pull secrets from Doppler -> .env.master -> fan out.
-----------------------------------------------------------------------------
 Doppler is the canonical source of truth. This regenerates the gitignored
 local dotenv cache so that BOTH of these keep working:
   - desktop-app / Cowork Claude sessions (no shell to prefix 'doppler run --')
   - Next.js builds (need web/.env.local present on disk)
 For a terminal session you can skip the cache entirely and just run:
   doppler run -- <command>

 Flow:  Doppler --(this)--> .env.master --(sync-envs.ps1)--> .env / web/.env.local / pipeline/.env

 Safety: - prints key NAMES + counts only, NEVER a value.
         - ABORTS (does not overwrite) if Doppler returns 0 app secrets.
         - sync-envs writes <file>.bak backups for instant rollback.
         - touches NOTHING in production: the DigitalOcean App env is separate.

 Usage:  pwsh scripts/doppler-pull-env.ps1            (pull + fan out)
         pwsh scripts/doppler-pull-env.ps1 -SkipSync  (write .env.master only)
=============================================================================
#>
[CmdletBinding()]
param(
  [switch]$SkipSync
)
$ErrorActionPreference = 'Stop'

$Root   = Split-Path -Parent $PSScriptRoot
$Master = Join-Path $Root '.env.master'

# --- 1. Doppler CLI present? ---
if (-not (Get-Command doppler -ErrorAction SilentlyContinue)) {
  Write-Host "ERROR: Doppler CLI not found on PATH."
  Write-Host "       Install:  winget install Doppler.doppler   (then restart the shell)"
  Write-Host "       Setup:    docs/doppler-secrets.md"
  exit 1
}

# --- 2. Download secrets (stdout only; values stay in memory, never logged) ---
Write-Host "Pulling secrets from Doppler (project/config come from 'doppler setup')..."
$rawArr = & doppler secrets download --no-file --format env-no-quotes
if ($LASTEXITCODE -ne 0 -or -not $rawArr) {
  Write-Host "ERROR: 'doppler secrets download' failed."
  Write-Host "       Run 'doppler login' and 'doppler setup' in this repo first."
  Write-Host "       See docs/doppler-secrets.md"
  exit 1
}

# --- 3. Keep KEY=value lines; drop comments + DOPPLER_* meta; collect names ---
$kept  = New-Object System.Collections.Generic.List[string]
$names = New-Object System.Collections.Generic.List[string]
foreach ($ln in @($rawArr)) {
  if ([string]::IsNullOrWhiteSpace($ln)) { continue }
  if ($ln.TrimStart().StartsWith('#'))   { continue }
  $idx = $ln.IndexOf('=')
  if ($idx -lt 1) { continue }
  $k = $ln.Substring(0, $idx).Trim()
  if ($k -like 'DOPPLER_*') { continue }   # Doppler meta keys, not app secrets
  $kept.Add($ln)
  $names.Add($k)
}

if ($kept.Count -eq 0) {
  Write-Host "ERROR: Doppler returned 0 app secrets - refusing to overwrite .env.master."
  Write-Host "       Check you are on the intended config:  doppler configure"
  exit 1
}

# --- 4. Write .env.master (UTF-8, no BOM, LF) so the sync + dotenv parsers stay happy ---
$stamp  = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$header = @(
  '# AUTO-GENERATED by scripts/doppler-pull-env.ps1 from Doppler.',
  '# Doppler is the source of truth - edit there, then re-pull. NEVER commit this file.',
  "# Pulled: $stamp"
  ''
)
$content   = (($header + $kept) -join "`n") + "`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($Master, $content, $utf8NoBom)

Write-Host ("Wrote .env.master with {0} keys:" -f $names.Count)
Write-Host ('  ' + (($names | Sort-Object) -join ', '))

# --- 5. Fan out to the downstream .env files ---
if ($SkipSync) {
  Write-Host "SkipSync set - not running sync-envs.ps1. Run it yourself to regenerate the 3 local .env files."
  exit 0
}
Write-Host ''
Write-Host 'Fanning out via scripts/sync-envs.ps1 ...'
& (Join-Path $PSScriptRoot 'sync-envs.ps1')
