#!/usr/bin/env bash
# ============================================================================
# doppler-pull-env.sh - pull secrets from Doppler -> .env.master -> fan out.
# ----------------------------------------------------------------------------
#   Doppler is the canonical source of truth. This regenerates the gitignored
#   local dotenv cache so desktop-app/Cowork Claude sessions AND Next.js builds
#   still see every key. For a terminal session, prefer:  doppler run -- <cmd>
#
#   Flow:  Doppler --(this)--> .env.master --(sync-envs.sh)--> .env / web/.env.local / pipeline/.env
#
#   Safety: - prints key NAMES + counts only, NEVER a value.
#           - ABORTS (no overwrite) if Doppler returns 0 app secrets.
#           - sync-envs writes <file>.bak backups for rollback.
#           - touches NOTHING in production (DigitalOcean App env is separate).
#
#   Usage:  bash scripts/doppler-pull-env.sh              (pull + fan out)
#           bash scripts/doppler-pull-env.sh --skip-sync  (write .env.master only)
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MASTER="$ROOT/.env.master"

command -v doppler >/dev/null 2>&1 || {
  echo "ERROR: Doppler CLI not found on PATH."
  echo "       Install + setup: docs/doppler-secrets.md"
  exit 1
}

echo "Pulling secrets from Doppler (project/config come from 'doppler setup')..."
TMP="$(mktemp)"; CLEAN="$(mktemp)"
trap 'rm -f "$TMP" "$CLEAN"' EXIT

if ! doppler secrets download --no-file --format env-no-quotes > "$TMP"; then
  echo "ERROR: 'doppler secrets download' failed."
  echo "       Run 'doppler login' and 'doppler setup' in this repo first. See docs/doppler-secrets.md"
  exit 1
fi

# Keep KEY=value; drop comments + DOPPLER_* meta keys.
grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$TMP" | grep -vE '^DOPPLER_' > "$CLEAN" || true
COUNT="$(wc -l < "$CLEAN" | tr -d ' ')"
if [ "$COUNT" -eq 0 ]; then
  echo "ERROR: Doppler returned 0 app secrets - refusing to overwrite .env.master."
  echo "       Check you are on the intended config:  doppler configure"
  exit 1
fi

{
  echo "# AUTO-GENERATED by scripts/doppler-pull-env.sh from Doppler."
  echo "# Doppler is the source of truth - edit there, then re-pull. NEVER commit this file."
  echo "# Pulled: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  cat "$CLEAN"
} > "$MASTER"

echo "Wrote .env.master with $COUNT keys:"
grep -oE '^[A-Za-z_][A-Za-z0-9_]*' "$MASTER" | sort | paste -sd ', ' -

if [ "${1:-}" = "--skip-sync" ]; then
  echo "--skip-sync set - not running sync-envs.sh."
  exit 0
fi

echo ""
echo "Fanning out via scripts/sync-envs.sh ..."
bash "$ROOT/scripts/sync-envs.sh"
