<#
=============================================================================
 sync-envs.ps1 - fan out .env.master to the three downstream .env files.
-----------------------------------------------------------------------------
   Single source of truth:  .\.env.master   (gitignored; NEVER commit)
   Targets:                 .\.env  .\web\.env.local  .\pipeline\.env

 Usage:   pwsh scripts/sync-envs.ps1        (or:  powershell -File scripts\sync-envs.ps1)

 Safety:  - prints key NAMES + status only - NEVER prints a secret value.
          - backs up each target to <file>.bak before overwriting (rollback).
          - warns on keys missing from master or still set to REPLACE_ME.
          - writes ASCII (no BOM) so dotenv parsers stay happy.
=============================================================================
#>
$ErrorActionPreference = 'Stop'

$Root   = Split-Path -Parent $PSScriptRoot
$Master = Join-Path $Root '.env.master'

if (-not (Test-Path $Master)) {
  Write-Host "ERROR: $Master not found."
  Write-Host "       Copy the template first:  Copy-Item .env.master.template .env.master  (then fill it in)"
  exit 1
}

# Parse master into a hashtable (values held in memory only, never printed).
$KV = @{}
foreach ($line in (Get-Content -LiteralPath $Master)) {
  $t = $line.Trim()
  if ($t -eq '' -or $t.StartsWith('#')) { continue }
  $t = $t -replace '^export\s+', ''
  $idx = $t.IndexOf('=')
  if ($idx -lt 1) { continue }
  $k = $t.Substring(0, $idx).Trim()
  $v = $t.Substring($idx + 1)
  $KV[$k] = $v
}

$script:Missing = 0
$script:Placeholder = 0
$script:Target = $null

function Start-Target([string]$path) {
  $script:Target = $path
  $dir = Split-Path -Parent $path
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  if (Test-Path $path) { Copy-Item -LiteralPath $path -Destination "$path.bak" -Force }
  $stamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
  $header = @(
    '# AUTO-GENERATED by scripts/sync-envs.ps1 from .env.master',
    '# Do not edit by hand - edit .env.master and re-run the sync. Do NOT commit.',
    "# Generated: $stamp",
    ''
  )
  Set-Content -LiteralPath $path -Value $header -Encoding ascii
  Write-Host "-> $path"
}

function Emit([string]$out, [string]$mkey) {
  if (-not $KV.ContainsKey($mkey)) {
    Write-Host "  ! $out  (missing in .env.master - skipped)"
    $script:Missing++
    return
  }
  $v = $KV[$mkey]
  if ($v -eq 'REPLACE_ME') {
    Write-Host "  ! $out  (still REPLACE_ME)"
    $script:Placeholder++
  } else {
    Write-Host "  + $out"
  }
  Add-Content -LiteralPath $script:Target -Value ("{0}={1}" -f $out, $v) -Encoding ascii
}

# --- [root] .\.env : DigitalOcean infra + Stripe + Scrapfly ------------------
Start-Target (Join-Path $Root '.env')
Emit 'DO_KEY'                 'DO_KEY'
Emit 'SCRAPFLY'               'SCRAPFLY'
Emit 'SCRAPFLY_KEY'           'SCRAPFLY_KEY'
Emit 'STRIPE_SECRET_KEY'      'STRIPE_SECRET_KEY'
Emit 'STRIPE_PUBLIC_KEY'      'STRIPE_PUBLIC_KEY'
Emit 'STRIPE_LIVE_SECRET_KEY' 'STRIPE_LIVE_SECRET_KEY'
Emit 'STRIPE_LIVE_PUBLIC_KEY' 'STRIPE_LIVE_PUBLIC_KEY'

# --- [web] .\web\.env.local : Next.js site / dashboard ----------------------
Start-Target (Join-Path $Root 'web\.env.local')
Emit 'NEXT_PUBLIC_SUPABASE_URL'                    'SUPABASE_URL'   # remap: canonical -> public
Emit 'NEXT_PUBLIC_SUPABASE_ANON_KEY'               'NEXT_PUBLIC_SUPABASE_ANON_KEY'
Emit 'SUPABASE_SERVICE_ROLE_KEY'                   'SUPABASE_SERVICE_ROLE_KEY'
Emit 'STRIPE_SECRET_KEY'                           'STRIPE_SECRET_KEY'
Emit 'STRIPE_WEBHOOK_SECRET'                        'STRIPE_WEBHOOK_SECRET'
Emit 'RESEND_API_KEY'                              'RESEND_API_KEY'
Emit 'RESEND_FROM_EMAIL'                           'RESEND_FROM_EMAIL'
Emit 'NEXT_PUBLIC_SITE_URL'                        'NEXT_PUBLIC_SITE_URL'
Emit 'SITE_URL'                                    'SITE_URL'
Emit 'NEXT_PUBLIC_POSTHOG_KEY'                     'NEXT_PUBLIC_POSTHOG_KEY'
Emit 'BING_INDEXNOW_KEY'                           'BING_INDEXNOW_KEY'
Emit 'CLERK_SECRET_KEY'                            'CLERK_SECRET_KEY'
Emit 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'           'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'
Emit 'NEXT_PUBLIC_CLERK_SIGN_IN_URL'               'NEXT_PUBLIC_CLERK_SIGN_IN_URL'
Emit 'NEXT_PUBLIC_CLERK_SIGN_UP_URL'               'NEXT_PUBLIC_CLERK_SIGN_UP_URL'
Emit 'NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL' 'NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL'
Emit 'NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL' 'NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL'
Emit 'E2E_FIXTURE_USER_EMAIL'                      'E2E_FIXTURE_USER_EMAIL'
Emit 'E2E_FIXTURE_USER_ID'                         'E2E_FIXTURE_USER_ID'
Emit 'TEST_SESSION_COOKIE'                         'TEST_SESSION_COOKIE'
Emit 'TEST_WAF_RUN_ID'                             'TEST_WAF_RUN_ID'

# --- [pipeline] .\pipeline\.env : Python LangGraph pipeline -----------------
Start-Target (Join-Path $Root 'pipeline\.env')
Emit 'SUPABASE_URL'                   'SUPABASE_URL'
Emit 'SUPABASE_SERVICE_ROLE_KEY'      'SUPABASE_SERVICE_ROLE_KEY'
Emit 'ANTHROPIC_API_KEY'              'ANTHROPIC_API_KEY'
Emit 'OPENAI_API_KEY'                 'OPENAI_API_KEY'
Emit 'PERPLEXITY_API_KEY'             'PERPLEXITY_API_KEY'
Emit 'GEMINI_API_KEY'                 'GEMINI_API_KEY'
Emit 'GEMINI_API_KEY_2'               'GEMINI_API_KEY_2'
Emit 'LANGSMITH_API_KEY'              'LANGSMITH_API_KEY'
Emit 'POSTHOG_PERSONAL_API_KEY'       'POSTHOG_PERSONAL_API_KEY'
Emit 'POSTHOG_PROJECT_ID'             'POSTHOG_PROJECT_ID'
Emit 'POSTHOG_HOST'                   'POSTHOG_HOST'
Emit 'GOBLIN_SUPABASE_ENABLED'        'GOBLIN_SUPABASE_ENABLED'
Emit 'GOBLIN_SUPABASE_CLIENT_ID'      'GOBLIN_SUPABASE_CLIENT_ID'
Emit 'GOBLIN_SUPABASE_OWNER_USER_ID'  'GOBLIN_SUPABASE_OWNER_USER_ID'
Emit 'GOBLIN_TRACE'                   'GOBLIN_TRACE'

Write-Host ''
Write-Host 'Done. Wrote 3 files (+ .bak backups).'
if ($script:Placeholder -gt 0) { Write-Host "WARNING: $script:Placeholder key(s) still REPLACE_ME - fill them in .env.master and re-run." }
if ($script:Missing -gt 0) { Write-Host "WARNING: $script:Missing key(s) missing from .env.master." }
Write-Host 'Reminder: production web/functions values also live in the DigitalOcean App env (set separately).'
Write-Host 'Never commit .env, .env.local, .env.master, or any .bak.'
