#!/usr/bin/env bash
# ============================================================================
# sync-envs.sh — fan out .env.master to the three downstream .env files.
# ----------------------------------------------------------------------------
#   Single source of truth:  ./.env.master   (gitignored; NEVER commit)
#   Targets:                 ./.env  ./web/.env.local  ./pipeline/.env
#
# Usage:   bash scripts/sync-envs.sh
#
# Safety:  - prints key NAMES + status only — NEVER prints a secret value.
#          - backs up each target to <file>.bak before overwriting (rollback).
#          - warns on keys missing from master or still set to REPLACE_ME.
# Portable: no associative arrays (works on macOS bash 3.2, Git-Bash, WSL).
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MASTER="$ROOT/.env.master"

if [ ! -f "$MASTER" ]; then
  echo "ERROR: $MASTER not found."
  echo "       Copy the template first:  cp .env.master.template .env.master  (then fill it in)"
  exit 1
fi

MISSING=0
PLACEHOLDER=0

# Fetch a single key's value from master. Echoes ONLY to the caller (captured),
# never to the console.
get_val() {
  grep -E "^[[:space:]]*(export[[:space:]]+)?$1=" "$MASTER" 2>/dev/null \
    | head -1 \
    | sed -E "s/^[[:space:]]*(export[[:space:]]+)?$1=//"
}

# emit OUTKEY MASTERKEY  -> append "OUTKEY=<value>" to $TARGET (value never logged)
emit() {
  local outkey="$1" mkey="$2" val
  val="$(get_val "$mkey")"
  if [ -z "$val" ]; then
    echo "  ! $outkey  (missing in .env.master — skipped)"
    MISSING=$((MISSING + 1))
    return
  fi
  if [ "$val" = "REPLACE_ME" ]; then
    echo "  ! $outkey  (still REPLACE_ME)"
    PLACEHOLDER=$((PLACEHOLDER + 1))
  else
    echo "  + $outkey"
  fi
  printf '%s=%s\n' "$outkey" "$val" >> "$TARGET"
}

start_target() {
  TARGET="$1"
  mkdir -p "$(dirname "$TARGET")"
  [ -f "$TARGET" ] && cp "$TARGET" "$TARGET.bak"
  {
    echo "# AUTO-GENERATED by scripts/sync-envs.sh from .env.master"
    echo "# Do not edit by hand — edit .env.master and re-run the sync. Do NOT commit."
    echo "# Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo ""
  } > "$TARGET"
  echo "→ $TARGET"
}

# --- [root] ./.env : DigitalOcean infra + Stripe + Scrapfly -----------------
start_target "$ROOT/.env"
emit DO_KEY                 DO_KEY
emit SCRAPFLY               SCRAPFLY
emit SCRAPFLY_KEY           SCRAPFLY_KEY
emit STRIPE_SECRET_KEY      STRIPE_SECRET_KEY
emit STRIPE_PUBLIC_KEY      STRIPE_PUBLIC_KEY
emit STRIPE_LIVE_SECRET_KEY STRIPE_LIVE_SECRET_KEY
emit STRIPE_LIVE_PUBLIC_KEY STRIPE_LIVE_PUBLIC_KEY

# --- [web] ./web/.env.local : Next.js site / dashboard ----------------------
start_target "$ROOT/web/.env.local"
emit NEXT_PUBLIC_SUPABASE_URL                    SUPABASE_URL   # remap: canonical -> public
emit NEXT_PUBLIC_SUPABASE_ANON_KEY               NEXT_PUBLIC_SUPABASE_ANON_KEY
emit SUPABASE_SERVICE_ROLE_KEY                   SUPABASE_SERVICE_ROLE_KEY
emit STRIPE_SECRET_KEY                           STRIPE_SECRET_KEY
emit STRIPE_WEBHOOK_SECRET                       STRIPE_WEBHOOK_SECRET
emit RESEND_API_KEY                              RESEND_API_KEY
emit RESEND_FROM_EMAIL                           RESEND_FROM_EMAIL
emit NEXT_PUBLIC_SITE_URL                        NEXT_PUBLIC_SITE_URL
emit SITE_URL                                    SITE_URL
emit NEXT_PUBLIC_POSTHOG_KEY                     NEXT_PUBLIC_POSTHOG_KEY
emit BING_INDEXNOW_KEY                           BING_INDEXNOW_KEY
emit CLERK_SECRET_KEY                            CLERK_SECRET_KEY
emit NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY           NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
emit NEXT_PUBLIC_CLERK_SIGN_IN_URL               NEXT_PUBLIC_CLERK_SIGN_IN_URL
emit NEXT_PUBLIC_CLERK_SIGN_UP_URL               NEXT_PUBLIC_CLERK_SIGN_UP_URL
emit NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
emit NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
emit E2E_FIXTURE_USER_EMAIL                      E2E_FIXTURE_USER_EMAIL
emit E2E_FIXTURE_USER_ID                         E2E_FIXTURE_USER_ID
emit TEST_SESSION_COOKIE                         TEST_SESSION_COOKIE
emit TEST_WAF_RUN_ID                             TEST_WAF_RUN_ID

# --- [pipeline] ./pipeline/.env : Python LangGraph pipeline -----------------
start_target "$ROOT/pipeline/.env"
emit SUPABASE_URL                   SUPABASE_URL
emit SUPABASE_SERVICE_ROLE_KEY      SUPABASE_SERVICE_ROLE_KEY
emit ANTHROPIC_API_KEY              ANTHROPIC_API_KEY
emit OPENAI_API_KEY                 OPENAI_API_KEY
emit PERPLEXITY_API_KEY             PERPLEXITY_API_KEY
emit GEMINI_API_KEY                 GEMINI_API_KEY
emit GEMINI_API_KEY_2               GEMINI_API_KEY_2
emit LANGSMITH_API_KEY              LANGSMITH_API_KEY
emit POSTHOG_PERSONAL_API_KEY       POSTHOG_PERSONAL_API_KEY
emit POSTHOG_PROJECT_ID             POSTHOG_PROJECT_ID
emit POSTHOG_HOST                   POSTHOG_HOST
emit GOBLIN_SUPABASE_ENABLED        GOBLIN_SUPABASE_ENABLED
emit GOBLIN_SUPABASE_CLIENT_ID      GOBLIN_SUPABASE_CLIENT_ID
emit GOBLIN_SUPABASE_OWNER_USER_ID  GOBLIN_SUPABASE_OWNER_USER_ID
emit GOBLIN_TRACE                   GOBLIN_TRACE

echo ""
echo "Done. Wrote 3 files (+ .bak backups)."
[ "$PLACEHOLDER" -gt 0 ] && echo "⚠️  $PLACEHOLDER key(s) still REPLACE_ME — fill them in .env.master and re-run."
[ "$MISSING" -gt 0 ] && echo "⚠️  $MISSING key(s) missing from .env.master."
echo "Reminder: production web/functions values also live in the DigitalOcean App env (set separately)."
echo "Never commit .env, .env.local, .env.master, or any .bak."
